### ISSUE TITLE
Doesn't work on resolutions higher than 1920x1080

### ISSUE THREAD

**Issue by kattjevfel** [ShayBox/Mon2Cam#3]
As previously [posted](https://github.com/TaPO4eg3D/discord-monitors-to-vc/issues/4) on the other repo, the tool will not work with a resolution over 1920x1080 (I presume), on 2560x1440 all I get is a black screen or sometimes a severely garbled static image.

I'm not sure if this is a bug in v4l2loopback or somewhere else, but I don't know how to test that.

**Comment by ShayBox** [comment]
Alright, I'll see what I can do

**Comment by ShayBox** [comment]
Okay, I updated the script, it seems both ffmpeg and v4l2loopback work fine with any resolution, the only problem I found was if the source was in use when the script went to remove the module it wouldn't remove the module and not remove the virtual device, keeping the original settings instead of taking on the new monitors settings.

Let me know if that fixed it

EDIT: I still can't get discord to show my second monitor, but `ffplay -f v4l2 /dev/video50` works, so I suspect it's just discord not working with my resolution monitor

**Comment by kattjevfel** [comment]
Right, yeah it seems to be a problem with Discord then, honestly I must've done something wrong while trying to open /dev/video* before because even without updating the script, it now works playing in both mpv and ffplay.

Would it be possible to downscale it to 1080p then? at least as an option, since Discord doesn't seem to support higher resolutions (which makes sense cuz webcams)

**Comment by ShayBox** [comment]
Discord doesn't like weird resolutions, it doesn't display 1366x768 either...  
I wouldn't know how to scale to the the nearest supported resolution, I wish they would just fix the bug, it's been 2 years

**Comment by kattjevfel** [comment]
What about a manual scale option? or is the issue about knowing how to scale at all? Anything's better than what we've got right now.

**Comment by kattjevfel** [comment]
I've taken it into my own hands and made a pull request with a setting to manually set the resolution. #4

**Comment by ShayBox** [comment]
Thanks :+1:
